repos:
  - repo: local
    hooks:
      - id: pre-commit-platform-safe-path-enforcer
        name: 'Check Path Separator'
        entry: hooks/check_paths.py
        language: script
        types: [python]